name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    name: Test on go ${{matrix.go_version}} and ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        go_version: ['1.18', '1.17', '>=1.18']
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go ${{matrix.go_version}}
      uses: actions/setup-go@v3
      with:
        go-version: ${{matrix.go_version}}
      
    - name: Build database
      run: docker-compose build
      
    - name: Create database
      run: docker-compose up -d

    - name: Test
      run: go test -v main_test.go
      
    - name: Build
      run: go build -v main.go
      
  build:
    name: Build on go ${{matrix.go_version}} and ${{matrix.os}}
    needs: test
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        go_version: ['1.18', '1.17', '>=1.18']
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: go build -v main.go
